layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 0
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: abhijeet.vaikar
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: abhijeetvaikar
  # mastodon: your_username
  medium: abhijeetvaikar
  stackoverflow: 1335594
  # telegram: your_username
  twitter: AbhijeetVaikar
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Testing
    web_url: https://github.com/topics/testing

  - name: Java
    web_url: https://github.com/topics/java
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/java/java.png

  - name: Go
    web_url: https://github.com/topics/go
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/go/go.png

  - name: Selenium
    web_url: https://github.com/topics/selenium

  - name: Appium
    web_url: https://github.com/topics/appium  

  - name: Continuous Integration
    web_url: https://github.com/topics/continuous-integration

  - name: Code Review
    web_url: https://github.com/topics/code-review

  - name: Code Quality
    web_url: https://github.com/topics/code-quality     

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png

  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/kubernetes/kubernetes.png

  - name: Maven
    web_url: https://github.com/topics/maven
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/maven/maven.png